name: mcprop
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cudatoolkit=10.2.89
  - freetype=2.11.0
  - giflib=5.2.1
  - intel-openmp=2021.4.0
  - jpeg=9d
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - ninja=1.10.2
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1l
  - pillow=8.4.0
  - pip=21.2.4
  - python=3.8.12
  - pytorch=1.7.1
  - readline=8.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - torchvision=0.2.2
  - typing_extensions=3.10.0.2
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==1.0.0
    - cachetools==4.2.4
    - charset-normalizer==2.0.7
    - click==8.0.3
    - git+https://github.com/openai/CLIP.git
    - filelock==3.4.0
    - ftfy==6.0.3
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.42.0
    - huggingface-hub==0.1.2
    - idna==3.3
    - importlib-metadata==4.8.2
    - joblib==1.1.0
    - markdown==3.3.6
    - oauthlib==3.1.1
    - packaging==21.3
    - pandas==1.3.4
    - protobuf==3.19.1
    - pyarrow==6.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.6
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - regex==2021.11.10
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - sacremoses==0.0.46
    - scikit-learn==1.0.1
    - scipy==1.7.2
    - sklearn==0.0
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - threadpoolctl==3.0.0
    - tokenizers==0.10.3
    - tqdm==4.62.3
    - transformers==4.12.5
    - urllib3==1.26.7
    - wcwidth==0.2.5
    - werkzeug==2.0.2
    - zipp==3.6.0

